name: bookly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:

  animated_text_kit: ^4.3.0
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^7.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_carousel: ^1.1.1
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2    

dev_dependencies:

  bloc_lint: ^0.3.0
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Hanuman/

  fonts:
    - family: Hanuman
      fonts:
        - asset: assets/fonts/Hanuman/Hanuman-Bold.ttf
        - asset: assets/fonts/Hanuman/Hanuman-Regular.ttf
