name: bookly
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  font_awesome_flutter: ^10.7.0
  dio: ^5.4.3+1
  google_fonts: ^7.0.2
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.2.6
  infinite_carousel: ^1.1.1
  carousel_slider: ^5.1.1
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Hanuman/


  fonts:
    - family: Hanuman
      fonts:
        - asset: assets/fonts/Hanuman/Hanuman-Bold.ttf
        - asset: assets/fonts/Hanuman/Hanuman-Regular.ttf